package dev.fxkit.core;

import java.net.URL;

/**
 * Entry point and metadata for the FXKit library.
 *
 * <p>Exposes the library version and the locations of FXKit's stylesheets.
 * Most applications do not call the stylesheet methods directly: use
 * {@link dev.fxkit.core.theme.ThemeManager#apply} instead, which installs them for you.
 */
public final class FxKit {

    /** Current library version. TODO: read from the POM via resource filtering. */
    public static final String VERSION = "0.1.0-SNAPSHOT";

    /** Design tokens: color scales, semantic colors, shadows and the dark theme. */
    private static final String TOKENS_CSS = "tokens.css";

    /** Utility classes (.bg-blue-500, .p-4, ...). Generated by tools/GenerateUtilities.java. */
    private static final String UTILITIES_CSS = "utilities.css";

    private FxKit() {
        // static utility class, not meant to be instantiated
    }

    /**
     * @return the FXKit version string
     */
    public static String version() {
        return VERSION;
    }

    /**
     * Returns the URL of FXKit's design-token stylesheet, ready to pass to
     * {@code scene.getStylesheets().add(...)}.
     *
     * @return the external form of the {@code tokens.css} URL
     * @throws IllegalStateException if the stylesheet is missing from the module
     * @see #stylesheet(String)
     */
    public static String tokensStylesheet() {
        return stylesheet(TOKENS_CSS);
    }

    /**
     * Returns the URL of FXKit's utility-class stylesheet. It only works together with
     * {@link #tokensStylesheet()}, because every utility reads a token.
     *
     * @return the external form of the {@code utilities.css} URL
     * @throws IllegalStateException if the stylesheet is missing from the module
     * @see #stylesheet(String)
     */
    public static String utilitiesStylesheet() {
        return stylesheet(UTILITIES_CSS);
    }

    /**
     * Why a method instead of asking for the file by path? In a named Java module,
     * resources inside a package are encapsulated: other modules cannot find them
     * unless the package is opened. Because this lookup runs inside
     * {@code dev.fxkit.core}, it succeeds and callers only receive the URL string.
     */
    private static String stylesheet(String name) {
        URL url = FxKit.class.getResource(name);
        if (url == null) {
            throw new IllegalStateException(
                    name + " not found in module dev.fxkit.core "
                            + "(expected at dev/fxkit/core/" + name + " in src/main/resources)");
        }
        return url.toExternalForm();
    }
}
